name: Build ZMK firmware

on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - .github/workflows/build.yml

jobs:
  build_left:
    uses: zmkfirmware/zmk/.github/workflows/build.yml@main
    with:
      board: nice_nano_v2
      shield: lily58_left

  build_right:
    uses: zmkfirmware/zmk/.github/workflows/build.yml@main
    with:
      board: nice_nano_v2
      shield: lily58_right
