name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip
          pip3 install west

      - name: Initialize west workspace
        run: |
          mkdir workspace
          cd workspace
          west init -l ../
          west update

      - name: Build Lily58 Left
        run: |
          cd workspace
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=lily58_left -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      - name: Upload Left Firmware
        uses: actions/upload-artifact@v4
        with:
          name: lily58_left
          path: workspace/build/zephyr/zmk.uf2

      - name: Build Lily58 Right
        run: |
          cd workspace
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=lily58_right -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      - name: Upload Right Firmware
        uses: actions/upload-artifact@v4
        with:
          name: lily58_right
          path: workspace/build/zephyr/zmk.uf2
